// flow-typed signature: 1738ac5a1a91679d36226ed1285c8401
// flow-typed version: <<STUB>>/mongoose_v^4.7.8/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongoose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongoose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongoose/lib/aggregate' {
  declare module.exports: any;
}

declare module 'mongoose/lib/browser' {
  declare module.exports: any;
}

declare module 'mongoose/lib/browserDocument' {
  declare module.exports: any;
}

declare module 'mongoose/lib/cast' {
  declare module.exports: any;
}

declare module 'mongoose/lib/collection' {
  declare module.exports: any;
}

declare module 'mongoose/lib/connection' {
  declare module.exports: any;
}

declare module 'mongoose/lib/connectionstate' {
  declare module.exports: any;
}

declare module 'mongoose/lib/document_provider' {
  declare module.exports: any;
}

declare module 'mongoose/lib/document_provider.web' {
  declare module.exports: any;
}

declare module 'mongoose/lib/document' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/browser/binary' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/browser/index' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/browser/objectid' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/browser/ReadPreference' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/index' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/index.web' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/node-mongodb-native/binary' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/node-mongodb-native/collection' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/node-mongodb-native/connection' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/node-mongodb-native/index' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/node-mongodb-native/objectid' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/node-mongodb-native/ReadPreference' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/browserMissingSchema' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/cast' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/disconnected' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/divergentArray' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/messages' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/missingSchema' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/objectExpected' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/overwriteModel' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/strict' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/validation' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/validator' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/version' {
  declare module.exports: any;
}

declare module 'mongoose/lib/ES6Promise' {
  declare module.exports: any;
}

declare module 'mongoose/lib/index' {
  declare module.exports: any;
}

declare module 'mongoose/lib/internal' {
  declare module.exports: any;
}

declare module 'mongoose/lib/model' {
  declare module.exports: any;
}

declare module 'mongoose/lib/promise_provider' {
  declare module.exports: any;
}

declare module 'mongoose/lib/promise' {
  declare module.exports: any;
}

declare module 'mongoose/lib/query' {
  declare module.exports: any;
}

declare module 'mongoose/lib/querycursor' {
  declare module.exports: any;
}

declare module 'mongoose/lib/queryhelpers' {
  declare module.exports: any;
}

declare module 'mongoose/lib/querystream' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/array' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/boolean' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/buffer' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/date' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/documentarray' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/embedded' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/index' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/mixed' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/number' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/objectid' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/operators/bitwise' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/operators/geospatial' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/operators/helpers' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/string' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schematype' {
  declare module.exports: any;
}

declare module 'mongoose/lib/services/common' {
  declare module.exports: any;
}

declare module 'mongoose/lib/services/setDefaultsOnInsert' {
  declare module.exports: any;
}

declare module 'mongoose/lib/services/updateValidators' {
  declare module.exports: any;
}

declare module 'mongoose/lib/statemachine' {
  declare module.exports: any;
}

declare module 'mongoose/lib/types/array' {
  declare module.exports: any;
}

declare module 'mongoose/lib/types/buffer' {
  declare module.exports: any;
}

declare module 'mongoose/lib/types/documentarray' {
  declare module.exports: any;
}

declare module 'mongoose/lib/types/embedded' {
  declare module.exports: any;
}

declare module 'mongoose/lib/types/index' {
  declare module.exports: any;
}

declare module 'mongoose/lib/types/objectid' {
  declare module.exports: any;
}

declare module 'mongoose/lib/types/subdocument' {
  declare module.exports: any;
}

declare module 'mongoose/lib/utils' {
  declare module.exports: any;
}

declare module 'mongoose/lib/virtualtype' {
  declare module.exports: any;
}

declare module 'mongoose/static' {
  declare module.exports: any;
}

declare module 'mongoose/website' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongoose/index' {
  declare module.exports: $Exports<'mongoose'>;
}
declare module 'mongoose/index.js' {
  declare module.exports: $Exports<'mongoose'>;
}
declare module 'mongoose/lib/aggregate.js' {
  declare module.exports: $Exports<'mongoose/lib/aggregate'>;
}
declare module 'mongoose/lib/browser.js' {
  declare module.exports: $Exports<'mongoose/lib/browser'>;
}
declare module 'mongoose/lib/browserDocument.js' {
  declare module.exports: $Exports<'mongoose/lib/browserDocument'>;
}
declare module 'mongoose/lib/cast.js' {
  declare module.exports: $Exports<'mongoose/lib/cast'>;
}
declare module 'mongoose/lib/collection.js' {
  declare module.exports: $Exports<'mongoose/lib/collection'>;
}
declare module 'mongoose/lib/connection.js' {
  declare module.exports: $Exports<'mongoose/lib/connection'>;
}
declare module 'mongoose/lib/connectionstate.js' {
  declare module.exports: $Exports<'mongoose/lib/connectionstate'>;
}
declare module 'mongoose/lib/document_provider.js' {
  declare module.exports: $Exports<'mongoose/lib/document_provider'>;
}
declare module 'mongoose/lib/document_provider.web.js' {
  declare module.exports: $Exports<'mongoose/lib/document_provider.web'>;
}
declare module 'mongoose/lib/document.js' {
  declare module.exports: $Exports<'mongoose/lib/document'>;
}
declare module 'mongoose/lib/drivers/browser/binary.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/browser/binary'>;
}
declare module 'mongoose/lib/drivers/browser/index.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/browser/index'>;
}
declare module 'mongoose/lib/drivers/browser/objectid.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/browser/objectid'>;
}
declare module 'mongoose/lib/drivers/browser/ReadPreference.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/browser/ReadPreference'>;
}
declare module 'mongoose/lib/drivers/index.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/index'>;
}
declare module 'mongoose/lib/drivers/index.web.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/index.web'>;
}
declare module 'mongoose/lib/drivers/node-mongodb-native/binary.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/node-mongodb-native/binary'>;
}
declare module 'mongoose/lib/drivers/node-mongodb-native/collection.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/node-mongodb-native/collection'>;
}
declare module 'mongoose/lib/drivers/node-mongodb-native/connection.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/node-mongodb-native/connection'>;
}
declare module 'mongoose/lib/drivers/node-mongodb-native/index.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/node-mongodb-native/index'>;
}
declare module 'mongoose/lib/drivers/node-mongodb-native/objectid.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/node-mongodb-native/objectid'>;
}
declare module 'mongoose/lib/drivers/node-mongodb-native/ReadPreference.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/node-mongodb-native/ReadPreference'>;
}
declare module 'mongoose/lib/error.js' {
  declare module.exports: $Exports<'mongoose/lib/error'>;
}
declare module 'mongoose/lib/error/browserMissingSchema.js' {
  declare module.exports: $Exports<'mongoose/lib/error/browserMissingSchema'>;
}
declare module 'mongoose/lib/error/cast.js' {
  declare module.exports: $Exports<'mongoose/lib/error/cast'>;
}
declare module 'mongoose/lib/error/disconnected.js' {
  declare module.exports: $Exports<'mongoose/lib/error/disconnected'>;
}
declare module 'mongoose/lib/error/divergentArray.js' {
  declare module.exports: $Exports<'mongoose/lib/error/divergentArray'>;
}
declare module 'mongoose/lib/error/messages.js' {
  declare module.exports: $Exports<'mongoose/lib/error/messages'>;
}
declare module 'mongoose/lib/error/missingSchema.js' {
  declare module.exports: $Exports<'mongoose/lib/error/missingSchema'>;
}
declare module 'mongoose/lib/error/objectExpected.js' {
  declare module.exports: $Exports<'mongoose/lib/error/objectExpected'>;
}
declare module 'mongoose/lib/error/overwriteModel.js' {
  declare module.exports: $Exports<'mongoose/lib/error/overwriteModel'>;
}
declare module 'mongoose/lib/error/strict.js' {
  declare module.exports: $Exports<'mongoose/lib/error/strict'>;
}
declare module 'mongoose/lib/error/validation.js' {
  declare module.exports: $Exports<'mongoose/lib/error/validation'>;
}
declare module 'mongoose/lib/error/validator.js' {
  declare module.exports: $Exports<'mongoose/lib/error/validator'>;
}
declare module 'mongoose/lib/error/version.js' {
  declare module.exports: $Exports<'mongoose/lib/error/version'>;
}
declare module 'mongoose/lib/ES6Promise.js' {
  declare module.exports: $Exports<'mongoose/lib/ES6Promise'>;
}
declare module 'mongoose/lib/index.js' {
  declare module.exports: $Exports<'mongoose/lib/index'>;
}
declare module 'mongoose/lib/internal.js' {
  declare module.exports: $Exports<'mongoose/lib/internal'>;
}
declare module 'mongoose/lib/model.js' {
  declare module.exports: $Exports<'mongoose/lib/model'>;
}
declare module 'mongoose/lib/promise_provider.js' {
  declare module.exports: $Exports<'mongoose/lib/promise_provider'>;
}
declare module 'mongoose/lib/promise.js' {
  declare module.exports: $Exports<'mongoose/lib/promise'>;
}
declare module 'mongoose/lib/query.js' {
  declare module.exports: $Exports<'mongoose/lib/query'>;
}
declare module 'mongoose/lib/querycursor.js' {
  declare module.exports: $Exports<'mongoose/lib/querycursor'>;
}
declare module 'mongoose/lib/queryhelpers.js' {
  declare module.exports: $Exports<'mongoose/lib/queryhelpers'>;
}
declare module 'mongoose/lib/querystream.js' {
  declare module.exports: $Exports<'mongoose/lib/querystream'>;
}
declare module 'mongoose/lib/schema.js' {
  declare module.exports: $Exports<'mongoose/lib/schema'>;
}
declare module 'mongoose/lib/schema/array.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/array'>;
}
declare module 'mongoose/lib/schema/boolean.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/boolean'>;
}
declare module 'mongoose/lib/schema/buffer.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/buffer'>;
}
declare module 'mongoose/lib/schema/date.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/date'>;
}
declare module 'mongoose/lib/schema/documentarray.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/documentarray'>;
}
declare module 'mongoose/lib/schema/embedded.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/embedded'>;
}
declare module 'mongoose/lib/schema/index.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/index'>;
}
declare module 'mongoose/lib/schema/mixed.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/mixed'>;
}
declare module 'mongoose/lib/schema/number.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/number'>;
}
declare module 'mongoose/lib/schema/objectid.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/objectid'>;
}
declare module 'mongoose/lib/schema/operators/bitwise.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/operators/bitwise'>;
}
declare module 'mongoose/lib/schema/operators/geospatial.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/operators/geospatial'>;
}
declare module 'mongoose/lib/schema/operators/helpers.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/operators/helpers'>;
}
declare module 'mongoose/lib/schema/string.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/string'>;
}
declare module 'mongoose/lib/schematype.js' {
  declare module.exports: $Exports<'mongoose/lib/schematype'>;
}
declare module 'mongoose/lib/services/common.js' {
  declare module.exports: $Exports<'mongoose/lib/services/common'>;
}
declare module 'mongoose/lib/services/setDefaultsOnInsert.js' {
  declare module.exports: $Exports<'mongoose/lib/services/setDefaultsOnInsert'>;
}
declare module 'mongoose/lib/services/updateValidators.js' {
  declare module.exports: $Exports<'mongoose/lib/services/updateValidators'>;
}
declare module 'mongoose/lib/statemachine.js' {
  declare module.exports: $Exports<'mongoose/lib/statemachine'>;
}
declare module 'mongoose/lib/types/array.js' {
  declare module.exports: $Exports<'mongoose/lib/types/array'>;
}
declare module 'mongoose/lib/types/buffer.js' {
  declare module.exports: $Exports<'mongoose/lib/types/buffer'>;
}
declare module 'mongoose/lib/types/documentarray.js' {
  declare module.exports: $Exports<'mongoose/lib/types/documentarray'>;
}
declare module 'mongoose/lib/types/embedded.js' {
  declare module.exports: $Exports<'mongoose/lib/types/embedded'>;
}
declare module 'mongoose/lib/types/index.js' {
  declare module.exports: $Exports<'mongoose/lib/types/index'>;
}
declare module 'mongoose/lib/types/objectid.js' {
  declare module.exports: $Exports<'mongoose/lib/types/objectid'>;
}
declare module 'mongoose/lib/types/subdocument.js' {
  declare module.exports: $Exports<'mongoose/lib/types/subdocument'>;
}
declare module 'mongoose/lib/utils.js' {
  declare module.exports: $Exports<'mongoose/lib/utils'>;
}
declare module 'mongoose/lib/virtualtype.js' {
  declare module.exports: $Exports<'mongoose/lib/virtualtype'>;
}
declare module 'mongoose/static.js' {
  declare module.exports: $Exports<'mongoose/static'>;
}
declare module 'mongoose/website.js' {
  declare module.exports: $Exports<'mongoose/website'>;
}
